# .streamlit/secrets.toml

[azure_sql]
server = "mygenaipoc.database.windows.net"
database = "genaipoc"
username = "rdg"
password = "Azure@4758"
driver = "{ODBC Driver 18 for SQL Server}"

[azure_storage]
connection_string = "DefaultEndpointsProtocol=https;AccountName=mygenaipoc;AccountKey=p8J69jdICgF4PZMnl9KmkBNxOx0lzg7PC815pdFywJqB1dqusZlsnAXg6PzpMiAXCopZCihYFuWn+AStxyPMcQ==;EndpointSuffix=core.windows.net"
container_name = "mygenaipoc"

[azure_openai]
api_key = "Cn2IWRpS5EpqWfPW5X3Y5HKXXotOjzTxWhSN9CqtCsBjazajvb2YJQQJ99BFACHYHv6XJ3w3AAAAACOGifdX"
api_type = "azure"
api_version = "2024-12-01-preview"
embedding_endpoint = "https://dasgu-mchng52g-eastus2.openai.azure.com/"
llm_endpoint = "https://dasgu-mchng52g-eastus2.openai.azure.com/"